version: '3'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test_db
      MYSQL_USER: panupongdeve
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - 8080:80
  web:
    image: php:7.2.2-apache
    container_name: php_web
    depends_on:
      - mysql
    volumes:
      - ./php/:/var/www/html/
    ports:
      - "4001:80"
    stdin_open: true
    tty: true